# Generated by Django 5.1.7 on 2025-05-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_veiculo_acessorio_veiculo_acessorios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='acessorios',
            field=models.ManyToManyField(blank=True, to='core.acessorio'),
        ),
    ]
